DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(30),
    email      VARCHAR(100) NOT NULL UNIQUE,
    login      VARCHAR(100) NOT NULL UNIQUE,
    birthday   DATE         NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS friend_status;
CREATE TABLE IF NOT EXISTS friend_status
(
    id          BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    status_name VARCHAR(20) NOT NULL CHECK (status_name IN ('WAITING_FOR_ANSWER',
                                                            'FRIEND',
                                                            'FRIEND_REQUEST'))
);

DROP TABLE IF EXISTS user_status;
    CREATE TABLE IF NOT EXISTS user_status
(
    user_id   BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, status_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (status_id) REFERENCES friend_status (id)
);

DROP TABLE IF EXISTS friends;
    CREATE TABLE IF NOT EXISTS friends
(
    user_id    INTEGER NOT NULL,
    friend_id  INTEGER NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    created_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (friend_id) REFERENCES users (id)
);

DROP TABLE IF EXISTS movie_rating;
    CREATE TABLE IF NOT EXISTS movie_rating
(
    id  BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    mpa VARCHAR(10) NOT NULL CHECK (mpa IN ('G',
                                            'PG',
                                            'PG-13',
                                            'R',
                                            'NC-17'))
);

DROP TABLE IF EXISTS movies;
    CREATE TABLE IF NOT EXISTS movies
(
    id          BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name        VARCHAR(200) NOT NULL UNIQUE,
    description VARCHAR(200),
    releaseDate DATE         NOT NULL,
    duration    INT          NOT NULL,
    mpa_id      BIGINT       NOT NULL,
    FOREIGN KEY (mpa_id) REFERENCES movie_rating (id)
);

DROP TABLE IF EXISTS genre;
    CREATE TABLE IF NOT EXISTS genre
(
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_type VARCHAR(50) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS movie_genre;
    CREATE TABLE IF NOT EXISTS movie_genre
(
    movie_id BIGINT NOT NULL REFERENCES movies (id),
    genre_id INT    NOT NULL REFERENCES genre (genre_id),
    PRIMARY KEY (movie_id, genre_id)
);

DROP TABLE IF EXISTS user_likes;
    CREATE TABLE IF NOT EXISTS user_likes
(
    user_id  BIGINT,
    movie_id BIGINT,
    liked_at TIMESTAMP,
    PRIMARY KEY (user_id, movie_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (movie_id) REFERENCES movies (id)
);